# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui


class DataBeen(object):
    def __init__(self):
        self.acc = None

    def set_data(self, data):
        self.acc = data

    def get_data(self):
        return self.acc


class inputDialog(QtWidgets.QDialog):
    def __init__(self, data, user_data):
        super().__init__()
        self.setObjectName("self")
        self.resize(420, 220)
        self.data = data

        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_3 = QtWidgets.QLineEdit(self)
        self.lineEdit_4 = QtWidgets.QLineEdit(self)

        self.label_4 = QtWidgets.QLabel(self)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_2 = QtWidgets.QLabel(self)
        self.label = QtWidgets.QLabel(self)

        self.pushButton = QtWidgets.QPushButton(self)

        self.comboBox = QtWidgets.QComboBox(self)

        self.setup_ui()

        if user_data is not None:
            self.set_data(user_data)

        self.set_event()

    def setup_ui(self):
        self.lineEdit.setGeometry(QtCore.QRect(190, 30, 70, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 70, 150, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 110, 170, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 150, 150, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label.setGeometry(QtCore.QRect(50, 35, 30, 12))
        self.label.setObjectName("label")
        self.label_2.setGeometry(QtCore.QRect(50, 75, 30, 12))
        self.label_2.setObjectName("label_2")
        self.label_3.setGeometry(QtCore.QRect(50, 115, 30, 12))
        self.label_3.setObjectName("label_3")
        self.label_4.setGeometry(QtCore.QRect(50, 155, 30, 12))
        self.label_4.setObjectName("label_4")
        self.pushButton.setGeometry(QtCore.QRect(330, 180, 70, 30))
        self.pushButton.setObjectName("pushButton")
        self.comboBox.setGeometry(QtCore.QRect(110, 30, 70, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslate_ui()
        QtCore.QMetaObject.connectSlotsByName(self)

    def set_data(self, user_data):
        self.comboBox.setCurrentIndex(user_data[0])
        self.lineEdit.setText(str(user_data[1]))
        self.lineEdit_2.setText(user_data[3])
        self.lineEdit_3.setText(user_data[4])
        self.lineEdit_4.setText(user_data[2])

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "请输入您的账号"))
        self.label.setText(_translate("self", "区服："))
        self.label_2.setText(_translate("self", "账号："))
        self.label_3.setText(_translate("self", "密码："))
        self.label_4.setText(_translate("self", "备注："))
        self.pushButton.setText(_translate("self", "确定"))
        self.comboBox.setItemText(0, _translate("Dialog", "选择大区"))
        self.comboBox.setItemText(1, _translate("Dialog", "4399"))
        self.comboBox.setItemText(2, _translate("Dialog", "7k7k"))

    def set_event(self):
        self.pushButton.clicked.connect(self.on_click)

    def on_click(self):
        self.data.set_data(
            [self.comboBox.currentIndex(), self.lineEdit.text(),
             self.lineEdit_4.text(), self.lineEdit_2.text(), self.lineEdit_3.text()])
        self.close()

    @staticmethod
    def on_run(user_data):
        # [[服务商,区服,显示名字,账号,密码], ]
        data = DataBeen()
        da = inputDialog(data, user_data)
        da.exec_()
        return data.get_data()


class loadingDlg(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(loadingDlg, self).__init__(parent)
        self.label = QtWidgets.QLabel('Red', self)
        self.setFixedSize(200, 200)
        self.setWindowOpacity(0.5)
        self.setWindowFlags(QtCore.Qt.Dialog | QtCore.Qt.CustomizeWindowHint)
        self.setContentsMargins(0, 0, 0, 0)
        self.label.setContentsMargins(0, 0, 0, 0)

        self.movie = QtGui.QMovie("loading.gif")
        self.label.setMovie(self.movie)
        self.movie.start()
        # self.label.show()

    def destroyDlg(self):
        self.close()

    def __del__(self):
        del self.label
        del self.movie
